version: '3'
services:
  v1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
    volumes:
      - imagenes-volumen-yachauyta:/var/www/services/images
volumes:
  imagenes-volumen-yachauyta: